
package vuelosfis.vista;
import java.util.ArrayList;
import vuelosfis.modelo.LogicaVuelos;


public class vistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaPrincipal.class.getName());

    public javax.swing.JButton getBtnContinuar() {
    return btnContinuar;
}
    public vistaPrincipal() {
        initComponents();
   


    cboTipoViaje.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[]{"Solo Ida", "Ida y Vuelta"}
    ));

    cboOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[]{"UIO - Quito", "AMS - Amsterdam", "MAD - Madrid", "JFK - New York"}
    ));

    cboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[]{"AMS - Amsterdam", "MAD - Madrid", "MIA - Miami"}
    ));

 
    espPasajeros.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

    checkEquipaje.setText("Equipaje Facturado (+$50)");
    checkMenu.setText("Menú Gourmet (+$50)");

  
    panelResultado.setLayout(
        new javax.swing.BoxLayout(panelResultado, javax.swing.BoxLayout.Y_AXIS)
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboTipoViaje = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboOrigen = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cboDestino = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dateIda = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dateVuelta = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        espPasajeros = new javax.swing.JSpinner();
        btnBuscarVuelo = new javax.swing.JButton();
        checkMenu = new javax.swing.JCheckBox();
        checkEquipaje = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelResultado = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaVuelos = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(250, 128, 128));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VuelosFIS");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("viaja comodamente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Viaje");
        jPanel2.add(jLabel3);

        cboTipoViaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solo Ida", "Ida y Vuelta" }));
        cboTipoViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoViajeActionPerformed(evt);
            }
        });
        jPanel2.add(cboTipoViaje);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Origen");
        jPanel2.add(jLabel4);

        cboOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboOrigenActionPerformed(evt);
            }
        });
        jPanel2.add(cboOrigen);

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Destino");
        jPanel2.add(jLabel5);

        cboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboDestino);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Ida");
        jPanel2.add(jLabel6);
        jPanel2.add(dateIda);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Vuelta");
        jPanel2.add(jLabel7);
        jPanel2.add(dateVuelta);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Pax");
        jPanel2.add(jLabel8);
        jPanel2.add(espPasajeros);

        btnBuscarVuelo.setBackground(new java.awt.Color(250, 128, 128));
        btnBuscarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarVuelo.setText("Buscar Vuelos");
        btnBuscarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVueloActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarVuelo);

        checkMenu.setText("Equipaje Facturado (+$50)");
        checkMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMenuActionPerformed(evt);
            }
        });

        checkEquipaje.setText("Menu (+$50)");
        checkEquipaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEquipajeActionPerformed(evt);
            }
        });

        panelResultado.setLayout(new javax.swing.BoxLayout(panelResultado, javax.swing.BoxLayout.LINE_AXIS));

        listaVuelos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        listaVuelos.setForeground(new java.awt.Color(153, 153, 153));
        listaVuelos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaVuelos);

        panelResultado.add(jScrollPane3);

        jScrollPane1.setViewportView(panelResultado);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        btnContinuar.setBackground(new java.awt.Color(0, 204, 51));
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar a Asientos y Pago");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnContinuar)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(checkMenu)
                .addGap(88, 88, 88)
                .addComponent(checkEquipaje, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkEquipaje)
                    .addComponent(checkMenu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContinuar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkEquipajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEquipajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEquipajeActionPerformed

    private void btnBuscarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVueloActionPerformed
 
    }//GEN-LAST:event_btnBuscarVueloActionPerformed

    private void cboTipoViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoViajeActionPerformed

    boolean idaVuelta = cboTipoViaje.getSelectedIndex() == 1;
    dateVuelta.setEnabled(idaVuelta);
    }//GEN-LAST:event_cboTipoViajeActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed

    if (listaVuelos.getSelectedIndex() >= 0) {
        
        DatosReserva.limpiar();
      
        try {
            DatosReserva.totalPasajeros = (int) espPasajeros.getValue();
        } catch (Exception e) {
      
             DatosReserva.totalPasajeros = 1;
        }
        
        String texto = listaVuelos.getSelectedValue(); 
        String[] partes = texto.split("\\|");
        
        DatosReserva.vueloGlobal = (partes.length > 0) ? partes[0].trim() : texto;
        DatosReserva.precioUnitario = (partes.length > 2) ? partes[2].trim() : "$0.00";
        DatosReserva.rutaGlobal = cboOrigen.getSelectedItem() + " - " + cboDestino.getSelectedItem();

        vistaCabina cabina = new vistaCabina();
        cabina.setVisible(true);
        cabina.setLocationRelativeTo(null);
        this.dispose();
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un vuelo.");
    }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void checkMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMenuActionPerformed

    private void cboOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarVuelo;
    public javax.swing.JButton btnContinuar;
    public javax.swing.JComboBox<String> cboDestino;
    public javax.swing.JComboBox<String> cboOrigen;
    public javax.swing.JComboBox<String> cboTipoViaje;
    private javax.swing.JCheckBox checkEquipaje;
    private javax.swing.JCheckBox checkMenu;
    public com.toedter.calendar.JDateChooser dateIda;
    public com.toedter.calendar.JDateChooser dateVuelta;
    public javax.swing.JSpinner espPasajeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JList<String> listaVuelos;
    private javax.swing.JPanel panelResultado;
    // End of variables declaration//GEN-END:variables
}

