
package vuelosfis.vista;
import javax.swing.JButton;
import java.awt.*;
import javax.swing.*;
public class vistaMapaAsientos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaMapaAsientos.class.getName());
    public String infoVuelo;
    public String infoPrecio;
    public String infoRuta;
    public String infoClase;
    private int maxPasajeros = 1;
    private int seleccionados = 0;
    public String asientoSeleccionado = "";

    private java.util.List<JButton> botones = new java.util.ArrayList<>();

    public vistaMapaAsientos() {
        initComponents();
    crearAsientos();
    jlabelContador.setText("0 de 0");
    btnConfirmar.setEnabled(false);
    }
    private void crearAsientos() {

    panelAsientos.setLayout(new GridLayout(16, 7, 15, 8));

    for (int fila = 1; fila <= 16; fila++) {

        for (char col = 'A'; col <= 'C'; col++) {
            panelAsientos.add(crearBoton(fila + "" + col));
        }

        panelAsientos.add(new JLabel(" " + fila + " ", SwingConstants.CENTER));

        for (char col = 'D'; col <= 'F'; col++) {
            panelAsientos.add(crearBoton(fila + "" + col));
        }
    }
    }
    private JButton crearBoton(String texto) {

    JButton btn = new JButton(texto);
    btn.setBackground(Color.WHITE);
    btn.setFocusPainted(false);

    btn.addActionListener(e -> toggleSeleccion(btn));

    botones.add(btn);
    return btn;
    }
    private void toggleSeleccion(JButton btn) {


    if (btn.getBackground().equals(Color.GREEN)) {
        btn.setBackground(Color.WHITE);
        seleccionados--;
    }

    else {
        if (seleccionados >= maxPasajeros) {
            return; 
        }
        btn.setBackground(Color.GREEN);
        seleccionados++;
        
        this.asientoSeleccionado = btn.getText();
    }

    jlabelContador.setText(seleccionados + " de " + maxPasajeros);
    btnConfirmar.setEnabled(seleccionados == maxPasajeros);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelAsientos = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        jlabelContador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(250, 128, 128));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione sus asientos ");

        jPanel2.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout panelAsientosLayout = new javax.swing.GroupLayout(panelAsientos);
        panelAsientos.setLayout(panelAsientosLayout);
        panelAsientosLayout.setHorizontalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        panelAsientosLayout.setVerticalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelAsientos);

        btnConfirmar.setBackground(new java.awt.Color(0, 204, 51));
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar Asiento");
        btnConfirmar.setEnabled(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jlabelContador.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(btnConfirmar))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jlabelContador))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelContador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmar)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
// 1. Obtener el asiento REAL (Borra el "4B" y pon esto)
    String asientoElegido = this.asientoSeleccionado; 
    
    // Validación por si acaso
    if (asientoElegido == null || asientoElegido.isEmpty()) {
        // Esto pasa si el usuario desmarca el asiento antes de confirmar
        asientoElegido = "Asiento " + (DatosReserva.contadorActual); 
    }

    // 2. Guardarlo en la lista
    DatosReserva.listaAsientos.add(asientoElegido);

    // 3. Ir a llenar datos... (esto déjalo igual)
    vistaDatosPasajero datos = new vistaDatosPasajero();
    datos.setVisible(true);
    datos.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaMapaAsientos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelContador;
    private javax.swing.JPanel panelAsientos;
    // End of variables declaration//GEN-END:variables
}
