package com.mycompany.biblioteca_digital.vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;

import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;
import com.mycompany.biblioteca_digital.modelo.Persona;
import com.mycompany.views.*;
/**
 *
 * @author ALEJANDRO
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private Persona usuarioLogueado;
    /**
     * Creates new form VentanaPrincipal
     */
public VentanaPrincipal() {
        initComponents();
        initCustomConfig();
    }

// Constructor que recibe el usuario logueado

   

    public VentanaPrincipal(Persona usuario) {
        this.usuarioLogueado = usuario;
        initComponents();
        initCustomConfig();
        configurarInterfazUsuario();
    }

    /**
     * Configuración personalizada 
     */
    private void initCustomConfig() {
        setLocationRelativeTo(null);
        setdate();
        InitStyles();
        setupIcons(); 
        InitContent(); // Carga la primera vista
    }

    /**
 * Configurar interfaz 
 */
private void configurarInterfazUsuario() {
    if (usuarioLogueado != null) {
        // Mostrar info del usuario en el titulo de la ventana
        setTitle("Sistema Biblioteca UET" + 
                 usuarioLogueado.getNombre() + " " + 
                 usuarioLogueado.getApellido() + 
                 " [" + usuarioLogueado.getTipo() + "]");
        
        System.out.println("Usuario logueado: " + usuarioLogueado.getNombre() + 
                          " - Tipo: " + usuarioLogueado.getTipo());
        
        // Si es USUARIO normal (no administrador)
        if ("USUARIO".equalsIgnoreCase(usuarioLogueado.getTipo())) {
            // Ocultar panel de USUARIOS (solo admin)
            boton3.setVisible(false);
             boton4.setVisible(false);
        }}
}
        
        // 1. Cargar y escalar la imagen 
private void setupIcons() {
        // Escalar Sello
        sello.setIcon(getScaledIcon("/imagenes/sello.png", 180, 160));
        sello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sello.setOpaque(false);
        sello.setText("");

        // Escalar Iconos de Botones 
        boton.setIcon(getScaledIcon("/imagenes/principal.png", 38, 39));
        boton1.setIcon(getScaledIcon("/imagenes/prestamo.png", 38, 39));
        boton2.setIcon(getScaledIcon("/imagenes/devolucion.png", 38, 39));
        boton3.setIcon(getScaledIcon("/imagenes/usuario.png", 38, 39));
        boton4.setIcon(getScaledIcon("/imagenes/libro.png", 38, 39));
        boton6.setIcon(getScaledIcon("/imagenes/reporte.png", 38, 39));
        boton7.setIcon(getScaledIcon("/imagenes/sala.png", 38, 39)); // o el ícono que uses
         boton8.setIcon(getScaledIcon("/imagenes/salirss.png", 38, 39)); // o el ícono que uses
}
private ImageIcon getScaledIcon(String path, int width, int height) {
        try {
            Image img = new ImageIcon(getClass().getResource(path)).getImage();
            return new ImageIcon(img.getScaledInstance(width, height, Image.SCALE_SMOOTH));
        } catch (Exception e) {
            System.err.println("No se pudo cargar la imagen: " + path);
            return null;
        }
    }

private void setdate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        etiqueta2.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }

    private void InitStyles() {
        etiqueta.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        etiqueta.setForeground(Color.black);
        etiqueta1.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        etiqueta1.setForeground(Color.white);
        etiqueta2.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        etiqueta2.setForeground(Color.white);
    }

    private void InitContent() {
        ShowJPanel(new vista1());
    }
 
    private void ShowJPanel(JPanel v1) {
    // Debug: Ver que panel se está cargando
    System.out.println("Cargando panel: " + v1.getClass().getSimpleName());
    
    v1.setSize(706, 457);
    v1.setLocation(0, 0);
    
    ventana.removeAll();
    ventana.setLayout(new BorderLayout());
    ventana.add(v1, BorderLayout.CENTER);
    ventana.revalidate();
    ventana.repaint();
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        etiqueta1 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        boton = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        sello = new javax.swing.JLabel();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        etiqueta = new javax.swing.JLabel();
        ventana = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1008, 719));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 640));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(750, 150));

        etiqueta1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        etiqueta1.setText("Administracion/Control/Biblioteca");

        etiqueta2.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        etiqueta2.setText("Hoy es Viernes 23 de Enero del 2026");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAutoscrolls(true);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        boton.setBackground(new java.awt.Color(0, 51, 102));
        boton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton.setForeground(new java.awt.Color(255, 255, 255));
        boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal.png"))); // NOI18N
        boton.setText("PRINCIPAL");
        boton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 7, 1, 8, new javax.swing.ImageIcon(getClass().getResource("/imagenes/principal.png")))); // NOI18N
        boton.setBorderPainted(false);
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton.setIconTextGap(35);
        boton.addActionListener(this::botonActionPerformed);

        boton6.setBackground(new java.awt.Color(0, 51, 102));
        boton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton6.setForeground(new java.awt.Color(255, 255, 255));
        boton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        boton6.setText("REPORTE");
        boton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 35, new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png")))); // NOI18N
        boton6.setBorderPainted(false);
        boton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton6.setIconTextGap(28);
        boton6.addActionListener(this::boton6ActionPerformed);

        boton1.setBackground(new java.awt.Color(0, 51, 102));
        boton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton1.setForeground(new java.awt.Color(255, 255, 255));
        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo.png"))); // NOI18N
        boton1.setText("PRESTAMOS");
        boton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 7, 1, 10, new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo.png")))); // NOI18N
        boton1.setBorderPainted(false);
        boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton1.setIconTextGap(20);
        boton1.addActionListener(this::boton1ActionPerformed);

        boton2.setBackground(new java.awt.Color(0, 51, 102));
        boton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton2.setForeground(new java.awt.Color(255, 255, 255));
        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/devolucion.png"))); // NOI18N
        boton2.setText("DEVOLUCIONES");
        boton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 28, 1, 15, new javax.swing.ImageIcon(getClass().getResource("/imagenes/devolucion.png")))); // NOI18N
        boton2.setBorderPainted(false);
        boton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton2.setIconTextGap(7);
        boton2.addActionListener(this::boton2ActionPerformed);

        boton3.setBackground(new java.awt.Color(0, 51, 102));
        boton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton3.setForeground(new java.awt.Color(255, 255, 255));
        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        boton3.setText("USUARIOS");
        boton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 28, new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png")))); // NOI18N
        boton3.setBorderPainted(false);
        boton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton3.setIconTextGap(25);
        boton3.addActionListener(this::boton3ActionPerformed);

        boton4.setBackground(new java.awt.Color(0, 51, 102));
        boton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton4.setForeground(new java.awt.Color(255, 255, 255));
        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro.png"))); // NOI18N
        boton4.setText("LIBROS");
        boton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 35, new java.awt.Color(0, 0, 0)));
        boton4.setBorderPainted(false);
        boton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton4.setIconTextGap(31);
        boton4.addActionListener(this::boton4ActionPerformed);

        sello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sello.png"))); // NOI18N
        sello.setText("1");
        sello.setBorder(new javax.swing.border.MatteBorder(null));

        boton7.setBackground(new java.awt.Color(0, 51, 102));
        boton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton7.setForeground(new java.awt.Color(255, 255, 255));
        boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        boton7.setText("SALAS");
        boton7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 35, new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png")))); // NOI18N
        boton7.setBorderPainted(false);
        boton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton7.setIconTextGap(28);
        boton7.addActionListener(this::boton7ActionPerformed);

        boton8.setBackground(new java.awt.Color(0, 51, 102));
        boton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton8.setForeground(new java.awt.Color(255, 255, 255));
        boton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        boton8.setText("CERRAR");
        boton8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 35, new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png")))); // NOI18N
        boton8.setBorderPainted(false);
        boton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton8.setIconTextGap(28);
        boton8.addActionListener(this::boton8ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(sello, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(sello, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        boton6.getAccessibleContext().setAccessibleName("Reporte");
        boton7.getAccessibleContext().setAccessibleName("Salas");

        etiqueta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etiqueta.setText("UNIDAD EDUCATIVA TUMBACO");

        ventana.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ventanaLayout = new javax.swing.GroupLayout(ventana);
        ventana.setLayout(ventanaLayout);
        ventanaLayout.setHorizontalGroup(
            ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ventanaLayout.setVerticalGroup(
            ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ventana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
                ShowJPanel(new vista2(usuarioLogueado));

    }//GEN-LAST:event_boton1ActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        // TODO add your handling code here:
                ShowJPanel(new vista1());

    }//GEN-LAST:event_botonActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        // TODO add your handling code here:
                ShowJPanel(new vista4(usuarioLogueado));

    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
                ShowJPanel(new vista3());

    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
               JPanel panelLibros = new JPanel(new java.awt.CardLayout());
               

    // Obtener el CardLayout
    java.awt.CardLayout cardLayout = (java.awt.CardLayout) panelLibros.getLayout();
    
    // Crear vista7 Y registroL
    vista5_1 panelListaLibros = new vista5_1(panelLibros, cardLayout);
    registroL panelRegistroLibros = new registroL(panelLibros, cardLayout);
    
    // Agregar ambos paneles al CardLayout
    panelLibros.add(panelListaLibros, "vista5_1");
    panelLibros.add(panelRegistroLibros, "registroL");
    
    // Mostrar vista7
    cardLayout.show(panelLibros, "vista5_1");
    
    // Mostrar el panel contenedor
    ShowJPanel(panelLibros);

    }//GEN-LAST:event_boton4ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        // TODO add your handling code here:
                ShowJPanel(new vista6(usuarioLogueado));

    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
          ShowJPanel(new vista7(usuarioLogueado));
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        // TODO add your handling code here:
         int confirmar = JOptionPane.showConfirmDialog(this,
        "¿Deseas cerrar sesión?",
        "Cerrar Sesión",
        JOptionPane.YES_NO_OPTION);

    if (confirmar == JOptionPane.YES_OPTION) {
        this.dispose(); // cierra SOLO esta ventana, no el programa
        new com.mycompany.biblioteca_digital.vista.VentanaLoading1().setVisible(true); // vuelve al login
    }
    }//GEN-LAST:event_boton8ActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         FlatMTMaterialLighterIJTheme.setup();

    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel sello;
    private javax.swing.JPanel ventana;
    // End of variables declaration//GEN-END:variables
}