/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

/**
 *
 * @author ALEJANDRO
 */
public class vista1 extends javax.swing.JPanel {

    /**
     * Creates new form vista1
     */
    public vista1() {
        initComponents();
uniforme.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foto.png")).getImage().getScaledInstance(300, 280, java.awt.Image.SCALE_SMOOTH)));

// 2. Forzar el centrado horizontal dentro del espacio del Label
uniforme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
// Para la Misión
parrafo.setBorder(null); 
parrafo.setOpaque(false); // Opcional: para que sea transparente y se vea el fondo blanco

// Para la Visión
parrafo1.setBorder(null);
parrafo1.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        uniforme = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        parrafo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        parrafo1 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(706, 457));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        uniforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foto.png"))); // NOI18N

        texto.setBackground(new java.awt.Color(0, 51, 102));
        texto.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        texto.setForeground(new java.awt.Color(0, 51, 102));
        texto.setText("MISIÓN:");

        texto2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        texto2.setForeground(new java.awt.Color(0, 51, 102));
        texto2.setText("VISIÓN:");

        parrafo.setColumns(20);
        parrafo.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        parrafo.setRows(5);
        parrafo.setText("Somos una Comunidad Educativa del valle de Tumbaco \n con la misión de brindar una educación integral, \n con calidad y calidez, que tiene como \n finalidad formar ciudadanos críticos, \n reflexivos, emprendedores y comprometidos \n con su patria, sociedad y  su entorno.");
        parrafo.setBorder(null);
        jScrollPane1.setViewportView(parrafo);

        jScrollPane2.setEnabled(false);
        jScrollPane2.setRowHeaderView(null);

        parrafo1.setColumns(20);
        parrafo1.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        parrafo1.setRows(5);
        parrafo1.setText("Al término de cinco años la UET \nserá una institución  pionera  en el valle, \nque brinde  una educación de calidad y calidez\n a nivel nacional e internacional.\n");
        parrafo1.setBorder(null);
        jScrollPane2.setViewportView(parrafo1);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(texto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(uniforme, javax.swing.GroupLayout.PREFERRED_SIZE, 294, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(texto2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addGap(66, 66, 66))
                    .addComponent(uniforme, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea parrafo;
    private javax.swing.JTextArea parrafo1;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel uniforme;
    // End of variables declaration//GEN-END:variables
}
